
interface _GlobalComponents {
      'Container': typeof import("../components/Container/index.vue")['default']
    'Deep': typeof import("../components/Deep/index.vue")['default']
    'Footer': typeof import("../components/Footer/index.vue")['default']
    'Header': typeof import("../components/Header/index.vue")['default']
    'History': typeof import("../components/History/index.vue")['default']
    'HomeTradeItem': typeof import("../components/Home/TradeItem.vue")['default']
    'Home': typeof import("../components/Home/index.vue")['default']
    'NotAuthModal': typeof import("../components/NotAuthModal/index.vue")['default']
    'Pagination': typeof import("../components/Pagination/index.vue")['default']
    'Price': typeof import("../components/Price/index.vue")['default']
    'PriceModal': typeof import("../components/PriceModal/index.vue")['default']
    'Profile': typeof import("../components/Profile/index.vue")['default']
    'RegisterModal': typeof import("../components/RegisterModal/index.vue")['default']
    'SignInModal': typeof import("../components/SignInModal/index.vue")['default']
    'Trade': typeof import("../components/Trade/index.vue")['default']
    'Watchlist': typeof import("../components/Watchlist/index.vue")['default']
    'Whale': typeof import("../components/Whale/index.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyContainer': typeof import("../components/Container/index.vue")['default']
    'LazyDeep': typeof import("../components/Deep/index.vue")['default']
    'LazyFooter': typeof import("../components/Footer/index.vue")['default']
    'LazyHeader': typeof import("../components/Header/index.vue")['default']
    'LazyHistory': typeof import("../components/History/index.vue")['default']
    'LazyHomeTradeItem': typeof import("../components/Home/TradeItem.vue")['default']
    'LazyHome': typeof import("../components/Home/index.vue")['default']
    'LazyNotAuthModal': typeof import("../components/NotAuthModal/index.vue")['default']
    'LazyPagination': typeof import("../components/Pagination/index.vue")['default']
    'LazyPrice': typeof import("../components/Price/index.vue")['default']
    'LazyPriceModal': typeof import("../components/PriceModal/index.vue")['default']
    'LazyProfile': typeof import("../components/Profile/index.vue")['default']
    'LazyRegisterModal': typeof import("../components/RegisterModal/index.vue")['default']
    'LazySignInModal': typeof import("../components/SignInModal/index.vue")['default']
    'LazyTrade': typeof import("../components/Trade/index.vue")['default']
    'LazyWatchlist': typeof import("../components/Watchlist/index.vue")['default']
    'LazyWhale': typeof import("../components/Whale/index.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Container: typeof import("../components/Container/index.vue")['default']
export const Deep: typeof import("../components/Deep/index.vue")['default']
export const Footer: typeof import("../components/Footer/index.vue")['default']
export const Header: typeof import("../components/Header/index.vue")['default']
export const History: typeof import("../components/History/index.vue")['default']
export const HomeTradeItem: typeof import("../components/Home/TradeItem.vue")['default']
export const Home: typeof import("../components/Home/index.vue")['default']
export const NotAuthModal: typeof import("../components/NotAuthModal/index.vue")['default']
export const Pagination: typeof import("../components/Pagination/index.vue")['default']
export const Price: typeof import("../components/Price/index.vue")['default']
export const PriceModal: typeof import("../components/PriceModal/index.vue")['default']
export const Profile: typeof import("../components/Profile/index.vue")['default']
export const RegisterModal: typeof import("../components/RegisterModal/index.vue")['default']
export const SignInModal: typeof import("../components/SignInModal/index.vue")['default']
export const Trade: typeof import("../components/Trade/index.vue")['default']
export const Watchlist: typeof import("../components/Watchlist/index.vue")['default']
export const Whale: typeof import("../components/Whale/index.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyContainer: typeof import("../components/Container/index.vue")['default']
export const LazyDeep: typeof import("../components/Deep/index.vue")['default']
export const LazyFooter: typeof import("../components/Footer/index.vue")['default']
export const LazyHeader: typeof import("../components/Header/index.vue")['default']
export const LazyHistory: typeof import("../components/History/index.vue")['default']
export const LazyHomeTradeItem: typeof import("../components/Home/TradeItem.vue")['default']
export const LazyHome: typeof import("../components/Home/index.vue")['default']
export const LazyNotAuthModal: typeof import("../components/NotAuthModal/index.vue")['default']
export const LazyPagination: typeof import("../components/Pagination/index.vue")['default']
export const LazyPrice: typeof import("../components/Price/index.vue")['default']
export const LazyPriceModal: typeof import("../components/PriceModal/index.vue")['default']
export const LazyProfile: typeof import("../components/Profile/index.vue")['default']
export const LazyRegisterModal: typeof import("../components/RegisterModal/index.vue")['default']
export const LazySignInModal: typeof import("../components/SignInModal/index.vue")['default']
export const LazyTrade: typeof import("../components/Trade/index.vue")['default']
export const LazyWatchlist: typeof import("../components/Watchlist/index.vue")['default']
export const LazyWhale: typeof import("../components/Whale/index.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
