// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/15/2025, 1:18:37 PM
const configMerger = require("/Users/icon/ico/polywhaler/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/icon/ico/polywhaler/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/polywhaler/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/polywhaler/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/polywhaler/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/polywhaler/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/polywhaler/plugins/**/*.{js,ts,mjs}","/Users/icon/ico/polywhaler/composables/**/*.{js,ts,mjs}","/Users/icon/ico/polywhaler/utils/**/*.{js,ts,mjs}","/Users/icon/ico/polywhaler/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/polywhaler/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/polywhaler/app.config.{js,ts,mjs}"] }));

module.exports = config
